# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\project\flight-control-simulation\QtAppV1\MainWelcome.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWelcome(object):
    def setupUi(self, MainWelcome):
        MainWelcome.setObjectName("MainWelcome")
        MainWelcome.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Img/a128.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWelcome.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWelcome)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 666))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pycharmButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pycharmButton.sizePolicy().hasHeightForWidth())
        self.pycharmButton.setSizePolicy(sizePolicy)
        self.pycharmButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pycharmButton.setMaximumSize(QtCore.QSize(80, 80))
        self.pycharmButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Img/loc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pycharmButton.setIcon(icon1)
        self.pycharmButton.setIconSize(QtCore.QSize(80, 80))
        self.pycharmButton.setFlat(True)
        self.pycharmButton.setObjectName("pycharmButton")
        self.gridLayout_3.addWidget(self.pycharmButton, 0, 2, 1, 1)
        self.mainSystemButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSystemButton.sizePolicy().hasHeightForWidth())
        self.mainSystemButton.setSizePolicy(sizePolicy)
        self.mainSystemButton.setMinimumSize(QtCore.QSize(80, 80))
        self.mainSystemButton.setMaximumSize(QtCore.QSize(80, 80))
        self.mainSystemButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Img/rh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mainSystemButton.setIcon(icon2)
        self.mainSystemButton.setIconSize(QtCore.QSize(80, 80))
        self.mainSystemButton.setFlat(True)
        self.mainSystemButton.setObjectName("mainSystemButton")
        self.gridLayout_3.addWidget(self.mainSystemButton, 0, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 10, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 7, 1, 1)
        self.flightButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flightButton.sizePolicy().hasHeightForWidth())
        self.flightButton.setSizePolicy(sizePolicy)
        self.flightButton.setMinimumSize(QtCore.QSize(80, 80))
        self.flightButton.setMaximumSize(QtCore.QSize(80, 80))
        self.flightButton.setText("")
        self.flightButton.setIcon(icon)
        self.flightButton.setIconSize(QtCore.QSize(80, 80))
        self.flightButton.setFlat(True)
        self.flightButton.setObjectName("flightButton")
        self.gridLayout_3.addWidget(self.flightButton, 0, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 0, 1, 1)
        self.matlabButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matlabButton.sizePolicy().hasHeightForWidth())
        self.matlabButton.setSizePolicy(sizePolicy)
        self.matlabButton.setMinimumSize(QtCore.QSize(80, 80))
        self.matlabButton.setMaximumSize(QtCore.QSize(80, 80))
        self.matlabButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Img/mat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.matlabButton.setIcon(icon3)
        self.matlabButton.setIconSize(QtCore.QSize(80, 80))
        self.matlabButton.setCheckable(False)
        self.matlabButton.setChecked(False)
        self.matlabButton.setAutoRepeat(False)
        self.matlabButton.setAutoDefault(False)
        self.matlabButton.setDefault(False)
        self.matlabButton.setFlat(True)
        self.matlabButton.setObjectName("matlabButton")
        self.gridLayout_3.addWidget(self.matlabButton, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        MainWelcome.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWelcome)
        self.statusbar.setObjectName("statusbar")
        MainWelcome.setStatusBar(self.statusbar)

        self.retranslateUi(MainWelcome)
        QtCore.QMetaObject.connectSlotsByName(MainWelcome)

    def retranslateUi(self, MainWelcome):
        _translate = QtCore.QCoreApplication.translate
        MainWelcome.setWindowTitle(_translate("MainWelcome", "飞行器多模态控制系统建模与仿真演示"))
        self.label.setText(_translate("MainWelcome", "飞行器多模态控制系统\n"
"建模与仿真环境"))
        self.label_4.setText(_translate("MainWelcome", "<html><head/><body><p><span style=\" color:#ffffff;\">控制律</span></p></body></html>"))
        self.label_6.setText(_translate("MainWelcome", "<html><head/><body><p><span style=\" color:#ffffff;\">联合仿真</span></p></body></html>"))
        self.label_3.setText(_translate("MainWelcome", "<html><head/><body><p><span style=\" color:#ffffff;\">地面站</span></p></body></html>"))
        self.label_7.setText(_translate("MainWelcome", "<html><head/><body><p><span style=\" color:#ffffff;\">飞行仿真</span></p></body></html>"))
        self.label_2.setText(_translate("MainWelcome", "<html><head/><body><p align=\"center\" style=\'line-height:70%\'><span style=\" color:#ffffff;\">南京航空航天大学</span></p><p align=\"center\" style=\'line-height:80%\'><span style=\" color:#ffffff; \">先进飞行控制研究课题组</span></p></body></html>"))
import res_rc
