# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\project\flight-control-simulation\QtAppV1\MainRhapsody.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainRhapsody(object):
    def setupUi(self, MainRhapsody):
        MainRhapsody.setObjectName("MainRhapsody")
        MainRhapsody.resize(1290, 893)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Img/BookmarkIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainRhapsody.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainRhapsody)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 1354, 831))
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName("splitter")
        self.a = QtWidgets.QFrame(self.splitter)
        self.a.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a.sizePolicy().hasHeightForWidth())
        self.a.setSizePolicy(sizePolicy)
        self.a.setMinimumSize(QtCore.QSize(450, 0))
        self.a.setMaximumSize(QtCore.QSize(650, 16777215))
        self.a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.a.setObjectName("a")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.a)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a1 = QtWidgets.QGroupBox(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a1.sizePolicy().hasHeightForWidth())
        self.a1.setSizePolicy(sizePolicy)
        self.a1.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a1.setFont(font)
        self.a1.setObjectName("a1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.a1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.a1)
        self.label_11.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.XEdit = QtWidgets.QLineEdit(self.a1)
        self.XEdit.setEnabled(False)
        self.XEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.XEdit.setFont(font)
        self.XEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.XEdit.setObjectName("XEdit")
        self.gridLayout_3.addWidget(self.XEdit, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.a1)
        self.label_10.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.YEdit = QtWidgets.QLineEdit(self.a1)
        self.YEdit.setEnabled(False)
        self.YEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.YEdit.setFont(font)
        self.YEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.YEdit.setObjectName("YEdit")
        self.gridLayout_3.addWidget(self.YEdit, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.a1)
        self.label_9.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 4, 1, 1)
        self.HEdit = QtWidgets.QLineEdit(self.a1)
        self.HEdit.setEnabled(False)
        self.HEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.HEdit.setFont(font)
        self.HEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HEdit.setObjectName("HEdit")
        self.gridLayout_3.addWidget(self.HEdit, 0, 5, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.a1)
        self.label_46.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 0, 6, 1, 1)
        self.VtEdit = QtWidgets.QLineEdit(self.a1)
        self.VtEdit.setEnabled(False)
        self.VtEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.VtEdit.setFont(font)
        self.VtEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VtEdit.setObjectName("VtEdit")
        self.gridLayout_3.addWidget(self.VtEdit, 0, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.a1)
        self.label_19.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.phiEdit = QtWidgets.QLineEdit(self.a1)
        self.phiEdit.setEnabled(False)
        self.phiEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.phiEdit.setFont(font)
        self.phiEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phiEdit.setObjectName("phiEdit")
        self.gridLayout_3.addWidget(self.phiEdit, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.a1)
        self.label_18.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 2, 1, 1)
        self.thetaEdit = QtWidgets.QLineEdit(self.a1)
        self.thetaEdit.setEnabled(False)
        self.thetaEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.thetaEdit.setFont(font)
        self.thetaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.thetaEdit.setObjectName("thetaEdit")
        self.gridLayout_3.addWidget(self.thetaEdit, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.a1)
        self.label_17.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 4, 1, 1)
        self.psiEdit = QtWidgets.QLineEdit(self.a1)
        self.psiEdit.setEnabled(False)
        self.psiEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.psiEdit.setFont(font)
        self.psiEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.psiEdit.setObjectName("psiEdit")
        self.gridLayout_3.addWidget(self.psiEdit, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.a1)
        self.label_8.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 6, 1, 1)
        self.alphaEdit = QtWidgets.QLineEdit(self.a1)
        self.alphaEdit.setEnabled(False)
        self.alphaEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.alphaEdit.setFont(font)
        self.alphaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout_3.addWidget(self.alphaEdit, 1, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.a1)
        self.label_7.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.betaEdit = QtWidgets.QLineEdit(self.a1)
        self.betaEdit.setEnabled(False)
        self.betaEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.betaEdit.setFont(font)
        self.betaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.betaEdit.setObjectName("betaEdit")
        self.gridLayout_3.addWidget(self.betaEdit, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.a1)
        self.label_20.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 2, 1, 1)
        self.pEdit = QtWidgets.QLineEdit(self.a1)
        self.pEdit.setEnabled(False)
        self.pEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pEdit.setFont(font)
        self.pEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pEdit.setObjectName("pEdit")
        self.gridLayout_3.addWidget(self.pEdit, 2, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.a1)
        self.label_21.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 4, 1, 1)
        self.qEdit = QtWidgets.QLineEdit(self.a1)
        self.qEdit.setEnabled(False)
        self.qEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.qEdit.setFont(font)
        self.qEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.qEdit.setObjectName("qEdit")
        self.gridLayout_3.addWidget(self.qEdit, 2, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.a1)
        self.label_45.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 2, 6, 1, 1)
        self.rEdit = QtWidgets.QLineEdit(self.a1)
        self.rEdit.setEnabled(False)
        self.rEdit.setMinimumSize(QtCore.QSize(50, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rEdit.setFont(font)
        self.rEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rEdit.setObjectName("rEdit")
        self.gridLayout_3.addWidget(self.rEdit, 2, 7, 1, 1)
        self.verticalLayout.addWidget(self.a1)
        self.c1 = QtWidgets.QHBoxLayout()
        self.c1.setSpacing(3)
        self.c1.setObjectName("c1")
        self.a2 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a2.setFont(font)
        self.a2.setFlat(False)
        self.a2.setCheckable(False)
        self.a2.setObjectName("a2")
        self.gridLayout = QtWidgets.QGridLayout(self.a2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_22 = QtWidgets.QLabel(self.a2)
        self.label_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 0, 1, 1)
        self.remoteControlModelLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remoteControlModelLed.sizePolicy().hasHeightForWidth())
        self.remoteControlModelLed.setSizePolicy(sizePolicy)
        self.remoteControlModelLed.setMinimumSize(QtCore.QSize(25, 25))
        self.remoteControlModelLed.setObjectName("remoteControlModelLed")
        self.gridLayout.addWidget(self.remoteControlModelLed, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.a2)
        self.label_44.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 0, 2, 1, 1)
        self.takeOffLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeOffLed.sizePolicy().hasHeightForWidth())
        self.takeOffLed.setSizePolicy(sizePolicy)
        self.takeOffLed.setMinimumSize(QtCore.QSize(25, 25))
        self.takeOffLed.setObjectName("takeOffLed")
        self.gridLayout.addWidget(self.takeOffLed, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.a2)
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 0, 1, 1)
        self.programeControlModelLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programeControlModelLed.sizePolicy().hasHeightForWidth())
        self.programeControlModelLed.setSizePolicy(sizePolicy)
        self.programeControlModelLed.setMinimumSize(QtCore.QSize(25, 25))
        self.programeControlModelLed.setObjectName("programeControlModelLed")
        self.gridLayout.addWidget(self.programeControlModelLed, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.a2)
        self.label_47.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 1, 2, 1, 1)
        self.landingLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingLed.sizePolicy().hasHeightForWidth())
        self.landingLed.setSizePolicy(sizePolicy)
        self.landingLed.setMinimumSize(QtCore.QSize(25, 25))
        self.landingLed.setObjectName("landingLed")
        self.gridLayout.addWidget(self.landingLed, 1, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.a2)
        self.label_31.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 2, 0, 1, 1)
        self.internalControlModelLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.internalControlModelLed.sizePolicy().hasHeightForWidth())
        self.internalControlModelLed.setSizePolicy(sizePolicy)
        self.internalControlModelLed.setMinimumSize(QtCore.QSize(25, 25))
        self.internalControlModelLed.setObjectName("internalControlModelLed")
        self.gridLayout.addWidget(self.internalControlModelLed, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.a2)
        self.label_32.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 2, 2, 1, 1)
        self.stopLed = QMyLed(self.a2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopLed.sizePolicy().hasHeightForWidth())
        self.stopLed.setSizePolicy(sizePolicy)
        self.stopLed.setMinimumSize(QtCore.QSize(25, 25))
        self.stopLed.setObjectName("stopLed")
        self.gridLayout.addWidget(self.stopLed, 2, 3, 1, 1)
        self.c1.addWidget(self.a2)
        self.a3 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a3.setFont(font)
        self.a3.setFlat(False)
        self.a3.setCheckable(False)
        self.a3.setObjectName("a3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.a3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_25 = QtWidgets.QLabel(self.a3)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.a3)
        self.label_40.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.a3)
        self.label_41.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 2, 0, 1, 1)
        self.turnLeftLed = QMyLed(self.a3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnLeftLed.sizePolicy().hasHeightForWidth())
        self.turnLeftLed.setSizePolicy(sizePolicy)
        self.turnLeftLed.setMinimumSize(QtCore.QSize(25, 25))
        self.turnLeftLed.setObjectName("turnLeftLed")
        self.gridLayout_2.addWidget(self.turnLeftLed, 0, 1, 1, 1)
        self.turnRightLed = QMyLed(self.a3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnRightLed.sizePolicy().hasHeightForWidth())
        self.turnRightLed.setSizePolicy(sizePolicy)
        self.turnRightLed.setMinimumSize(QtCore.QSize(25, 25))
        self.turnRightLed.setObjectName("turnRightLed")
        self.gridLayout_2.addWidget(self.turnRightLed, 1, 1, 1, 1)
        self.keepDirectLed = QMyLed(self.a3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepDirectLed.sizePolicy().hasHeightForWidth())
        self.keepDirectLed.setSizePolicy(sizePolicy)
        self.keepDirectLed.setMinimumSize(QtCore.QSize(25, 25))
        self.keepDirectLed.setObjectName("keepDirectLed")
        self.gridLayout_2.addWidget(self.keepDirectLed, 2, 1, 1, 1)
        self.c1.addWidget(self.a3)
        self.a4 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a4.setFont(font)
        self.a4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.a4.setFlat(False)
        self.a4.setCheckable(False)
        self.a4.setObjectName("a4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.a4)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.a4)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 2, 1, 1)
        self.keepPostureLed = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepPostureLed.sizePolicy().hasHeightForWidth())
        self.keepPostureLed.setSizePolicy(sizePolicy)
        self.keepPostureLed.setMinimumSize(QtCore.QSize(25, 25))
        self.keepPostureLed.setObjectName("keepPostureLed")
        self.gridLayout_4.addWidget(self.keepPostureLed, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.a4)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 3, 1)
        self.keepHeightLed = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepHeightLed.sizePolicy().hasHeightForWidth())
        self.keepHeightLed.setSizePolicy(sizePolicy)
        self.keepHeightLed.setMinimumSize(QtCore.QSize(25, 25))
        self.keepHeightLed.setObjectName("keepHeightLed")
        self.gridLayout_4.addWidget(self.keepHeightLed, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.a4)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.climb2Led = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.climb2Led.sizePolicy().hasHeightForWidth())
        self.climb2Led.setSizePolicy(sizePolicy)
        self.climb2Led.setMinimumSize(QtCore.QSize(25, 25))
        self.climb2Led.setObjectName("climb2Led")
        self.gridLayout_4.addWidget(self.climb2Led, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.a4)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.a4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 5, 2, 1, 1)
        self.climb1Led = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.climb1Led.sizePolicy().hasHeightForWidth())
        self.climb1Led.setSizePolicy(sizePolicy)
        self.climb1Led.setMinimumSize(QtCore.QSize(25, 25))
        self.climb1Led.setObjectName("climb1Led")
        self.gridLayout_4.addWidget(self.climb1Led, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.a4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 2, 3, 1)
        self.decline1Led = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decline1Led.sizePolicy().hasHeightForWidth())
        self.decline1Led.setSizePolicy(sizePolicy)
        self.decline1Led.setMinimumSize(QtCore.QSize(25, 25))
        self.decline1Led.setObjectName("decline1Led")
        self.gridLayout_4.addWidget(self.decline1Led, 1, 1, 3, 1)
        self.decline2Led = QMyLed(self.a4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decline2Led.sizePolicy().hasHeightForWidth())
        self.decline2Led.setSizePolicy(sizePolicy)
        self.decline2Led.setMinimumSize(QtCore.QSize(25, 25))
        self.decline2Led.setObjectName("decline2Led")
        self.gridLayout_4.addWidget(self.decline2Led, 1, 3, 3, 1)
        self.c1.addWidget(self.a4)
        self.c1.setStretch(1, 2)
        self.c1.setStretch(2, 5)
        self.verticalLayout.addLayout(self.c1)
        self.a5 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a5.setFont(font)
        self.a5.setFlat(False)
        self.a5.setCheckable(False)
        self.a5.setObjectName("a5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.a5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtWidgets.QLabel(self.a5)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 1)
        self.bigCartLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigCartLed.sizePolicy().hasHeightForWidth())
        self.bigCartLed.setSizePolicy(sizePolicy)
        self.bigCartLed.setMinimumSize(QtCore.QSize(25, 25))
        self.bigCartLed.setObjectName("bigCartLed")
        self.gridLayout_5.addWidget(self.bigCartLed, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.a5)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 2, 1, 1)
        self.ratedLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratedLed.sizePolicy().hasHeightForWidth())
        self.ratedLed.setSizePolicy(sizePolicy)
        self.ratedLed.setMinimumSize(QtCore.QSize(25, 25))
        self.ratedLed.setObjectName("ratedLed")
        self.gridLayout_5.addWidget(self.ratedLed, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.a5)
        self.label_42.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 4, 1, 1)
        self.cruiseLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cruiseLed.sizePolicy().hasHeightForWidth())
        self.cruiseLed.setSizePolicy(sizePolicy)
        self.cruiseLed.setMinimumSize(QtCore.QSize(25, 25))
        self.cruiseLed.setObjectName("cruiseLed")
        self.gridLayout_5.addWidget(self.cruiseLed, 0, 5, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.a5)
        self.label_43.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 0, 6, 1, 1)
        self.slowTrainLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slowTrainLed.sizePolicy().hasHeightForWidth())
        self.slowTrainLed.setSizePolicy(sizePolicy)
        self.slowTrainLed.setMinimumSize(QtCore.QSize(25, 25))
        self.slowTrainLed.setObjectName("slowTrainLed")
        self.gridLayout_5.addWidget(self.slowTrainLed, 0, 7, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.a5)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 8, 1, 1)
        self.idlingLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idlingLed.sizePolicy().hasHeightForWidth())
        self.idlingLed.setSizePolicy(sizePolicy)
        self.idlingLed.setMinimumSize(QtCore.QSize(25, 25))
        self.idlingLed.setObjectName("idlingLed")
        self.gridLayout_5.addWidget(self.idlingLed, 0, 9, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.a5)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.parkingLed = QMyLed(self.a5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parkingLed.sizePolicy().hasHeightForWidth())
        self.parkingLed.setSizePolicy(sizePolicy)
        self.parkingLed.setMinimumSize(QtCore.QSize(25, 25))
        self.parkingLed.setObjectName("parkingLed")
        self.gridLayout_5.addWidget(self.parkingLed, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.a5)
        self.c2 = QtWidgets.QHBoxLayout()
        self.c2.setSpacing(3)
        self.c2.setObjectName("c2")
        self.a6 = QtWidgets.QGroupBox(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a6.sizePolicy().hasHeightForWidth())
        self.a6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a6.setFont(font)
        self.a6.setObjectName("a6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.a6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.programeControlModelButton = QtWidgets.QPushButton(self.a6)
        self.programeControlModelButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.programeControlModelButton.setFont(font)
        self.programeControlModelButton.setObjectName("programeControlModelButton")
        self.gridLayout_6.addWidget(self.programeControlModelButton, 1, 0, 1, 1)
        self.remoteControlModelButton = QtWidgets.QPushButton(self.a6)
        self.remoteControlModelButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.remoteControlModelButton.setFont(font)
        self.remoteControlModelButton.setObjectName("remoteControlModelButton")
        self.gridLayout_6.addWidget(self.remoteControlModelButton, 0, 0, 1, 1)
        self.internalControlModelButton = QtWidgets.QPushButton(self.a6)
        self.internalControlModelButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.internalControlModelButton.setFont(font)
        self.internalControlModelButton.setObjectName("internalControlModelButton")
        self.gridLayout_6.addWidget(self.internalControlModelButton, 2, 0, 1, 1)
        self.takeOffButton = QtWidgets.QPushButton(self.a6)
        self.takeOffButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.takeOffButton.setFont(font)
        self.takeOffButton.setObjectName("takeOffButton")
        self.gridLayout_6.addWidget(self.takeOffButton, 0, 1, 1, 1)
        self.landingButton = QtWidgets.QPushButton(self.a6)
        self.landingButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.landingButton.setFont(font)
        self.landingButton.setObjectName("landingButton")
        self.gridLayout_6.addWidget(self.landingButton, 1, 1, 1, 1)
        self.c2.addWidget(self.a6)
        self.a7 = QtWidgets.QGroupBox(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a7.sizePolicy().hasHeightForWidth())
        self.a7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a7.setFont(font)
        self.a7.setObjectName("a7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.a7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.keepDirectButton = QtWidgets.QPushButton(self.a7)
        self.keepDirectButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.keepDirectButton.setFont(font)
        self.keepDirectButton.setObjectName("keepDirectButton")
        self.gridLayout_7.addWidget(self.keepDirectButton, 2, 0, 1, 1)
        self.turnRightButton = QtWidgets.QPushButton(self.a7)
        self.turnRightButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.turnRightButton.setFont(font)
        self.turnRightButton.setObjectName("turnRightButton")
        self.gridLayout_7.addWidget(self.turnRightButton, 1, 0, 1, 1)
        self.turnLeftButton = QtWidgets.QPushButton(self.a7)
        self.turnLeftButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.turnLeftButton.setFont(font)
        self.turnLeftButton.setObjectName("turnLeftButton")
        self.gridLayout_7.addWidget(self.turnLeftButton, 0, 0, 1, 1)
        self.c2.addWidget(self.a7)
        self.a8 = QtWidgets.QGroupBox(self.a)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a8.sizePolicy().hasHeightForWidth())
        self.a8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a8.setFont(font)
        self.a8.setObjectName("a8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.a8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.climb1Button = QtWidgets.QPushButton(self.a8)
        self.climb1Button.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.climb1Button.setFont(font)
        self.climb1Button.setObjectName("climb1Button")
        self.gridLayout_8.addWidget(self.climb1Button, 0, 0, 1, 1)
        self.climb2Button = QtWidgets.QPushButton(self.a8)
        self.climb2Button.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.climb2Button.setFont(font)
        self.climb2Button.setObjectName("climb2Button")
        self.gridLayout_8.addWidget(self.climb2Button, 0, 1, 1, 1)
        self.decline1Button = QtWidgets.QPushButton(self.a8)
        self.decline1Button.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.decline1Button.setFont(font)
        self.decline1Button.setObjectName("decline1Button")
        self.gridLayout_8.addWidget(self.decline1Button, 1, 0, 1, 1)
        self.decline2Button = QtWidgets.QPushButton(self.a8)
        self.decline2Button.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.decline2Button.setFont(font)
        self.decline2Button.setObjectName("decline2Button")
        self.gridLayout_8.addWidget(self.decline2Button, 1, 1, 1, 1)
        self.keepHeightButton = QtWidgets.QPushButton(self.a8)
        self.keepHeightButton.setMinimumSize(QtCore.QSize(60, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.keepHeightButton.setFont(font)
        self.keepHeightButton.setObjectName("keepHeightButton")
        self.gridLayout_8.addWidget(self.keepHeightButton, 2, 0, 1, 1)
        self.c2.addWidget(self.a8)
        self.c2.setStretch(0, 5)
        self.c2.setStretch(1, 2)
        self.c2.setStretch(2, 5)
        self.verticalLayout.addLayout(self.c2)
        self.a9 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a9.setFont(font)
        self.a9.setFlat(False)
        self.a9.setCheckable(False)
        self.a9.setObjectName("a9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.a9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.bigCartButton = QtWidgets.QPushButton(self.a9)
        self.bigCartButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bigCartButton.setFont(font)
        self.bigCartButton.setObjectName("bigCartButton")
        self.gridLayout_10.addWidget(self.bigCartButton, 0, 0, 1, 1)
        self.ratedButton = QtWidgets.QPushButton(self.a9)
        self.ratedButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ratedButton.setFont(font)
        self.ratedButton.setObjectName("ratedButton")
        self.gridLayout_10.addWidget(self.ratedButton, 0, 1, 1, 1)
        self.cruiseButton = QtWidgets.QPushButton(self.a9)
        self.cruiseButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.cruiseButton.setFont(font)
        self.cruiseButton.setObjectName("cruiseButton")
        self.gridLayout_10.addWidget(self.cruiseButton, 0, 2, 1, 1)
        self.slowTrainButton = QtWidgets.QPushButton(self.a9)
        self.slowTrainButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.slowTrainButton.setFont(font)
        self.slowTrainButton.setObjectName("slowTrainButton")
        self.gridLayout_10.addWidget(self.slowTrainButton, 0, 3, 1, 1)
        self.idlingButton = QtWidgets.QPushButton(self.a9)
        self.idlingButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.idlingButton.setFont(font)
        self.idlingButton.setObjectName("idlingButton")
        self.gridLayout_10.addWidget(self.idlingButton, 0, 4, 1, 1)
        self.preStopButton = QtWidgets.QPushButton(self.a9)
        self.preStopButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.preStopButton.setFont(font)
        self.preStopButton.setObjectName("preStopButton")
        self.gridLayout_10.addWidget(self.preStopButton, 1, 0, 1, 1)
        self.parkingButton = QtWidgets.QPushButton(self.a9)
        self.parkingButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.parkingButton.setFont(font)
        self.parkingButton.setObjectName("parkingButton")
        self.gridLayout_10.addWidget(self.parkingButton, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.a9)
        self.a10 = QtWidgets.QGroupBox(self.a)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.a10.setFont(font)
        self.a10.setFlat(False)
        self.a10.setCheckable(False)
        self.a10.setObjectName("a10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.a10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setParametersButton = QtWidgets.QPushButton(self.a10)
        self.setParametersButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.setParametersButton.setFont(font)
        self.setParametersButton.setObjectName("setParametersButton")
        self.horizontalLayout_2.addWidget(self.setParametersButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.saveConfButton = QtWidgets.QPushButton(self.a10)
        self.saveConfButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.saveConfButton.setFont(font)
        self.saveConfButton.setObjectName("saveConfButton")
        self.horizontalLayout_2.addWidget(self.saveConfButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.saveFigButton = QtWidgets.QPushButton(self.a10)
        self.saveFigButton.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.saveFigButton.setFont(font)
        self.saveFigButton.setObjectName("saveFigButton")
        self.horizontalLayout_2.addWidget(self.saveFigButton)
        self.verticalLayout.addWidget(self.a10)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 4)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 1)
        self.b = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b.sizePolicy().hasHeightForWidth())
        self.b.setSizePolicy(sizePolicy)
        self.b.setMinimumSize(QtCore.QSize(900, 0))
        self.b.setObjectName("b")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.b)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QGroupBox(self.b)
        self.b1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.b1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.threeDView = QmyFigureCanvas(self.b1)
        self.threeDView.setObjectName("threeDView")
        self.verticalLayout_3.addWidget(self.threeDView)
        self.mapView = QtWidgets.QWidget(self.b1)
        self.mapView.setObjectName("mapView")
        self.verticalLayout_3.addWidget(self.mapView)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 2)
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QGroupBox(self.b)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy)
        self.b2.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.b2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.heightView = QmyFigureCanvas(self.b2)
        self.heightView.setObjectName("heightView")
        self.verticalLayout_2.addWidget(self.heightView)
        self.thetaView = QmyFigureCanvas(self.b2)
        self.thetaView.setObjectName("thetaView")
        self.verticalLayout_2.addWidget(self.thetaView)
        self.phiView = QmyFigureCanvas(self.b2)
        self.phiView.setObjectName("phiView")
        self.verticalLayout_2.addWidget(self.phiView)
        self.psiView = QmyFigureCanvas(self.b2)
        self.psiView.setObjectName("psiView")
        self.verticalLayout_2.addWidget(self.psiView)
        self.horizontalLayout.addWidget(self.b2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        MainRhapsody.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainRhapsody)
        self.statusbar.setObjectName("statusbar")
        MainRhapsody.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainRhapsody)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainRhapsody)
        self.action_3.setObjectName("action_3")
        self.actParameterTitle = QtWidgets.QAction(MainRhapsody)
        self.actParameterTitle.setObjectName("actParameterTitle")
        self.actParameterLegend = QtWidgets.QAction(MainRhapsody)
        self.actParameterLegend.setObjectName("actParameterLegend")
        self.actParamenterLabel = QtWidgets.QAction(MainRhapsody)
        self.actParamenterLabel.setObjectName("actParamenterLabel")
        self.action_7 = QtWidgets.QAction(MainRhapsody)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainRhapsody)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainRhapsody)
        self.action_9.setObjectName("action_9")

        self.retranslateUi(MainRhapsody)
        QtCore.QMetaObject.connectSlotsByName(MainRhapsody)

    def retranslateUi(self, MainRhapsody):
        _translate = QtCore.QCoreApplication.translate
        MainRhapsody.setWindowTitle(_translate("MainRhapsody", "联合仿真系统"))
        self.a1.setTitle(_translate("MainRhapsody", "参数显示"))
        self.label_11.setText(_translate("MainRhapsody", "距离:"))
        self.XEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_10.setText(_translate("MainRhapsody", "侧位:"))
        self.YEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_9.setText(_translate("MainRhapsody", "高度:"))
        self.HEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_46.setText(_translate("MainRhapsody", "空速:"))
        self.VtEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_19.setText(_translate("MainRhapsody", "滚转角:"))
        self.phiEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_18.setText(_translate("MainRhapsody", "俯仰角:"))
        self.thetaEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_17.setText(_translate("MainRhapsody", "偏航角:"))
        self.psiEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_8.setText(_translate("MainRhapsody", "迎角:"))
        self.alphaEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_7.setText(_translate("MainRhapsody", "侧滑角:"))
        self.betaEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_20.setText(_translate("MainRhapsody", "P:"))
        self.pEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_21.setText(_translate("MainRhapsody", "Q:"))
        self.qEdit.setText(_translate("MainRhapsody", "  0"))
        self.label_45.setText(_translate("MainRhapsody", "R:"))
        self.rEdit.setText(_translate("MainRhapsody", "  0"))
        self.a2.setTitle(_translate("MainRhapsody", "控制模式状态"))
        self.label_22.setText(_translate("MainRhapsody", "遥控"))
        self.label_44.setText(_translate("MainRhapsody", "起飞"))
        self.label_33.setText(_translate("MainRhapsody", "程控"))
        self.label_47.setText(_translate("MainRhapsody", "着陆"))
        self.label_31.setText(_translate("MainRhapsody", "内控"))
        self.label_32.setText(_translate("MainRhapsody", "停止"))
        self.a3.setTitle(_translate("MainRhapsody", "横侧向状态"))
        self.label_25.setText(_translate("MainRhapsody", "左转"))
        self.label_40.setText(_translate("MainRhapsody", "右转"))
        self.label_41.setText(_translate("MainRhapsody", "定向"))
        self.a4.setTitle(_translate("MainRhapsody", "纵向状态"))
        self.label_12.setText(_translate("MainRhapsody", "爬升2"))
        self.label_5.setText(_translate("MainRhapsody", "下滑1"))
        self.label_4.setText(_translate("MainRhapsody", "爬升1"))
        self.label_6.setText(_translate("MainRhapsody", "定高\n"
"平飞"))
        self.label_15.setText(_translate("MainRhapsody", "姿态\n"
"保持"))
        self.label_3.setText(_translate("MainRhapsody", "下滑2"))
        self.a5.setTitle(_translate("MainRhapsody", "发动机状态"))
        self.label_23.setText(_translate("MainRhapsody", "大车"))
        self.label_28.setText(_translate("MainRhapsody", "额定"))
        self.label_42.setText(_translate("MainRhapsody", "巡航"))
        self.label_43.setText(_translate("MainRhapsody", "慢车"))
        self.label_13.setText(_translate("MainRhapsody", "怠速"))
        self.label_14.setText(_translate("MainRhapsody", "停车"))
        self.a6.setTitle(_translate("MainRhapsody", "控制模式"))
        self.programeControlModelButton.setText(_translate("MainRhapsody", "程控"))
        self.remoteControlModelButton.setText(_translate("MainRhapsody", "遥控"))
        self.internalControlModelButton.setText(_translate("MainRhapsody", "内控"))
        self.takeOffButton.setText(_translate("MainRhapsody", "起飞"))
        self.landingButton.setText(_translate("MainRhapsody", "着陆"))
        self.a7.setTitle(_translate("MainRhapsody", "横侧向控制"))
        self.keepDirectButton.setText(_translate("MainRhapsody", "定向"))
        self.turnRightButton.setText(_translate("MainRhapsody", "右转"))
        self.turnLeftButton.setText(_translate("MainRhapsody", "左转"))
        self.a8.setTitle(_translate("MainRhapsody", "纵向控制"))
        self.climb1Button.setText(_translate("MainRhapsody", "爬升1"))
        self.climb2Button.setText(_translate("MainRhapsody", "爬升2"))
        self.decline1Button.setText(_translate("MainRhapsody", "下滑1"))
        self.decline2Button.setText(_translate("MainRhapsody", "下滑2"))
        self.keepHeightButton.setText(_translate("MainRhapsody", "定高平飞"))
        self.a9.setTitle(_translate("MainRhapsody", "发动机控制"))
        self.bigCartButton.setText(_translate("MainRhapsody", "大车"))
        self.ratedButton.setText(_translate("MainRhapsody", "额定"))
        self.cruiseButton.setText(_translate("MainRhapsody", "巡航"))
        self.slowTrainButton.setText(_translate("MainRhapsody", "慢车"))
        self.idlingButton.setText(_translate("MainRhapsody", "怠速"))
        self.preStopButton.setText(_translate("MainRhapsody", "预停"))
        self.parkingButton.setText(_translate("MainRhapsody", "停车"))
        self.a10.setTitle(_translate("MainRhapsody", "参数信息"))
        self.setParametersButton.setText(_translate("MainRhapsody", "参数装订"))
        self.saveConfButton.setText(_translate("MainRhapsody", "保存数据"))
        self.saveFigButton.setText(_translate("MainRhapsody", "保存图像"))
        self.b1.setTitle(_translate("MainRhapsody", "三维航迹"))
        self.b2.setTitle(_translate("MainRhapsody", "飞行参数曲线"))
        self.action_2.setText(_translate("MainRhapsody", "关于软件"))
        self.action_3.setText(_translate("MainRhapsody", "关于课题组"))
        self.actParameterTitle.setText(_translate("MainRhapsody", "飞行参数图标字体设置"))
        self.actParameterLegend.setText(_translate("MainRhapsody", "飞行参数图例字体设置"))
        self.actParamenterLabel.setText(_translate("MainRhapsody", "飞行参数数据标签字体设置"))
        self.action_7.setText(_translate("MainRhapsody", "地图数据标签字体设置"))
        self.action_8.setText(_translate("MainRhapsody", "地图图例字体设置"))
        self.action_9.setText(_translate("MainRhapsody", "地图图标字体设置"))
from QMyLed import QMyLed
from myFigureCanvas import QmyFigureCanvas
import res_rc
