# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\project\flight-control-simulation\QtAppV1\SetParameters.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setParameter(object):
    def setupUi(self, setParameter):
        setParameter.setObjectName("setParameter")
        setParameter.resize(554, 300)
        setParameter.setMaximumSize(QtCore.QSize(600, 350))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        setParameter.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Img/settings_128px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        setParameter.setWindowIcon(icon)
        setParameter.setSizeGripEnabled(False)
        setParameter.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(setParameter)
        self.verticalLayout.setContentsMargins(12, 6, 12, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(6, -1, 6, -1)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.getClimb1Theta = QtWidgets.QCheckBox(setParameter)
        self.getClimb1Theta.setChecked(True)
        self.getClimb1Theta.setObjectName("getClimb1Theta")
        self.gridLayout.addWidget(self.getClimb1Theta, 1, 0, 1, 1)
        self.setClimb1Theta = QtWidgets.QDoubleSpinBox(setParameter)
        self.setClimb1Theta.setWrapping(False)
        self.setClimb1Theta.setFrame(True)
        self.setClimb1Theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setClimb1Theta.setMinimum(-1000.0)
        self.setClimb1Theta.setMaximum(1000.0)
        self.setClimb1Theta.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setClimb1Theta.setProperty("value", 20.0)
        self.setClimb1Theta.setObjectName("setClimb1Theta")
        self.gridLayout.addWidget(self.setClimb1Theta, 1, 1, 1, 1)
        self.getAll = QtWidgets.QCheckBox(setParameter)
        self.getAll.setChecked(True)
        self.getAll.setObjectName("getAll")
        self.gridLayout.addWidget(self.getAll, 0, 0, 1, 1)
        self.getHight = QtWidgets.QCheckBox(setParameter)
        self.getHight.setChecked(True)
        self.getHight.setObjectName("getHight")
        self.gridLayout.addWidget(self.getHight, 1, 2, 1, 1)
        self.setClimb2Theta = QtWidgets.QDoubleSpinBox(setParameter)
        self.setClimb2Theta.setWrapping(False)
        self.setClimb2Theta.setFrame(True)
        self.setClimb2Theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setClimb2Theta.setMinimum(-1000.0)
        self.setClimb2Theta.setMaximum(1000.0)
        self.setClimb2Theta.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setClimb2Theta.setProperty("value", 4.0)
        self.setClimb2Theta.setObjectName("setClimb2Theta")
        self.gridLayout.addWidget(self.setClimb2Theta, 3, 1, 1, 1)
        self.getTurnLeftPsi = QtWidgets.QCheckBox(setParameter)
        self.getTurnLeftPsi.setChecked(True)
        self.getTurnLeftPsi.setObjectName("getTurnLeftPsi")
        self.gridLayout.addWidget(self.getTurnLeftPsi, 3, 2, 1, 1)
        self.getDecline1Theta = QtWidgets.QCheckBox(setParameter)
        self.getDecline1Theta.setChecked(True)
        self.getDecline1Theta.setObjectName("getDecline1Theta")
        self.gridLayout.addWidget(self.getDecline1Theta, 4, 0, 1, 1)
        self.getClimb2Theta = QtWidgets.QCheckBox(setParameter)
        self.getClimb2Theta.setChecked(True)
        self.getClimb2Theta.setObjectName("getClimb2Theta")
        self.gridLayout.addWidget(self.getClimb2Theta, 3, 0, 1, 1)
        self.setTurnLeftPsi = QtWidgets.QDoubleSpinBox(setParameter)
        self.setTurnLeftPsi.setWrapping(False)
        self.setTurnLeftPsi.setFrame(True)
        self.setTurnLeftPsi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setTurnLeftPsi.setMinimum(-1000.0)
        self.setTurnLeftPsi.setMaximum(1000.0)
        self.setTurnLeftPsi.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setTurnLeftPsi.setProperty("value", -9.0)
        self.setTurnLeftPsi.setObjectName("setTurnLeftPsi")
        self.gridLayout.addWidget(self.setTurnLeftPsi, 3, 3, 1, 1)
        self.setDecline1Theta = QtWidgets.QDoubleSpinBox(setParameter)
        self.setDecline1Theta.setWrapping(False)
        self.setDecline1Theta.setFrame(True)
        self.setDecline1Theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setDecline1Theta.setMinimum(-1000.0)
        self.setDecline1Theta.setMaximum(1000.0)
        self.setDecline1Theta.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setDecline1Theta.setProperty("value", -20.0)
        self.setDecline1Theta.setObjectName("setDecline1Theta")
        self.gridLayout.addWidget(self.setDecline1Theta, 4, 1, 1, 1)
        self.getDecline2Theta = QtWidgets.QCheckBox(setParameter)
        self.getDecline2Theta.setChecked(True)
        self.getDecline2Theta.setObjectName("getDecline2Theta")
        self.gridLayout.addWidget(self.getDecline2Theta, 5, 0, 1, 1)
        self.setTurnRightPsi = QtWidgets.QDoubleSpinBox(setParameter)
        self.setTurnRightPsi.setWrapping(False)
        self.setTurnRightPsi.setFrame(True)
        self.setTurnRightPsi.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setTurnRightPsi.setMinimum(-1000.0)
        self.setTurnRightPsi.setMaximum(1000.0)
        self.setTurnRightPsi.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setTurnRightPsi.setProperty("value", 9.0)
        self.setTurnRightPsi.setObjectName("setTurnRightPsi")
        self.gridLayout.addWidget(self.setTurnRightPsi, 4, 3, 1, 1)
        self.setDecline2Theta = QtWidgets.QDoubleSpinBox(setParameter)
        self.setDecline2Theta.setWrapping(False)
        self.setDecline2Theta.setFrame(True)
        self.setDecline2Theta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setDecline2Theta.setMinimum(-1000.0)
        self.setDecline2Theta.setMaximum(1000.0)
        self.setDecline2Theta.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setDecline2Theta.setProperty("value", -2.0)
        self.setDecline2Theta.setObjectName("setDecline2Theta")
        self.gridLayout.addWidget(self.setDecline2Theta, 5, 1, 1, 1)
        self.setHight = QtWidgets.QDoubleSpinBox(setParameter)
        self.setHight.setWrapping(False)
        self.setHight.setFrame(True)
        self.setHight.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.setHight.setMinimum(-1000.0)
        self.setHight.setMaximum(1000.0)
        self.setHight.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.setHight.setProperty("value", 70.0)
        self.setHight.setObjectName("setHight")
        self.gridLayout.addWidget(self.setHight, 1, 3, 1, 1)
        self.getTurnRightPsi = QtWidgets.QCheckBox(setParameter)
        self.getTurnRightPsi.setChecked(True)
        self.getTurnRightPsi.setObjectName("getTurnRightPsi")
        self.gridLayout.addWidget(self.getTurnRightPsi, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnReset = QtWidgets.QPushButton(setParameter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout.addWidget(self.btnReset)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnOK = QtWidgets.QPushButton(setParameter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnCancel = QtWidgets.QPushButton(setParameter)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(setParameter)
        QtCore.QMetaObject.connectSlotsByName(setParameter)

    def retranslateUi(self, setParameter):
        _translate = QtCore.QCoreApplication.translate
        setParameter.setWindowTitle(_translate("setParameter", "参数设置"))
        self.getClimb1Theta.setText(_translate("setParameter", "爬升1俯仰角"))
        self.getAll.setText(_translate("setParameter", "全选"))
        self.getHight.setText(_translate("setParameter", "高度"))
        self.getTurnLeftPsi.setText(_translate("setParameter", "左转偏航角"))
        self.getDecline1Theta.setText(_translate("setParameter", "下滑1俯仰角"))
        self.getClimb2Theta.setText(_translate("setParameter", "爬升2俯仰角"))
        self.getDecline2Theta.setText(_translate("setParameter", "下滑2俯仰角"))
        self.getTurnRightPsi.setText(_translate("setParameter", "右转偏航角"))
        self.btnReset.setText(_translate("setParameter", "重置"))
        self.btnOK.setText(_translate("setParameter", "确定"))
        self.btnCancel.setText(_translate("setParameter", "取消"))
import res_rc
