# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainRhapsody.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainRhapsody(object):
    def setupUi(self, MainRhapsody):
        MainRhapsody.setObjectName("MainRhapsody")
        MainRhapsody.resize(1339, 917)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Img/BookmarkIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainRhapsody.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainRhapsody)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1231, 673))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(350, 0))
        self.frame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setContentsMargins(0, -1, 12, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 4, 1, 1)
        self.climb1Led = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.climb1Led.sizePolicy().hasHeightForWidth())
        self.climb1Led.setSizePolicy(sizePolicy)
        self.climb1Led.setMinimumSize(QtCore.QSize(31, 31))
        self.climb1Led.setObjectName("climb1Led")
        self.gridLayout_2.addWidget(self.climb1Led, 0, 3, 1, 1)
        self.keepDirectLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepDirectLed.sizePolicy().hasHeightForWidth())
        self.keepDirectLed.setSizePolicy(sizePolicy)
        self.keepDirectLed.setMinimumSize(QtCore.QSize(31, 31))
        self.keepDirectLed.setObjectName("keepDirectLed")
        self.gridLayout_2.addWidget(self.keepDirectLed, 2, 5, 1, 1)
        self.turnLeftLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnLeftLed.sizePolicy().hasHeightForWidth())
        self.turnLeftLed.setSizePolicy(sizePolicy)
        self.turnLeftLed.setMinimumSize(QtCore.QSize(31, 31))
        self.turnLeftLed.setObjectName("turnLeftLed")
        self.gridLayout_2.addWidget(self.turnLeftLed, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.climb2Led = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.climb2Led.sizePolicy().hasHeightForWidth())
        self.climb2Led.setSizePolicy(sizePolicy)
        self.climb2Led.setMinimumSize(QtCore.QSize(31, 31))
        self.climb2Led.setObjectName("climb2Led")
        self.gridLayout_2.addWidget(self.climb2Led, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.decline2Led = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decline2Led.sizePolicy().hasHeightForWidth())
        self.decline2Led.setSizePolicy(sizePolicy)
        self.decline2Led.setMinimumSize(QtCore.QSize(31, 31))
        self.decline2Led.setObjectName("decline2Led")
        self.gridLayout_2.addWidget(self.decline2Led, 3, 3, 1, 1)
        self.takeOffLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.takeOffLed.sizePolicy().hasHeightForWidth())
        self.takeOffLed.setSizePolicy(sizePolicy)
        self.takeOffLed.setMinimumSize(QtCore.QSize(31, 31))
        self.takeOffLed.setObjectName("takeOffLed")
        self.gridLayout_2.addWidget(self.takeOffLed, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.turnRightLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turnRightLed.sizePolicy().hasHeightForWidth())
        self.turnRightLed.setSizePolicy(sizePolicy)
        self.turnRightLed.setMinimumSize(QtCore.QSize(31, 31))
        self.turnRightLed.setObjectName("turnRightLed")
        self.gridLayout_2.addWidget(self.turnRightLed, 1, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 1)
        self.decline1Led = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decline1Led.sizePolicy().hasHeightForWidth())
        self.decline1Led.setSizePolicy(sizePolicy)
        self.decline1Led.setMinimumSize(QtCore.QSize(31, 31))
        self.decline1Led.setObjectName("decline1Led")
        self.gridLayout_2.addWidget(self.decline1Led, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.landingLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.landingLed.sizePolicy().hasHeightForWidth())
        self.landingLed.setSizePolicy(sizePolicy)
        self.landingLed.setMinimumSize(QtCore.QSize(31, 31))
        self.landingLed.setObjectName("landingLed")
        self.gridLayout_2.addWidget(self.landingLed, 1, 1, 1, 1)
        self.programeControlLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programeControlLed.sizePolicy().hasHeightForWidth())
        self.programeControlLed.setSizePolicy(sizePolicy)
        self.programeControlLed.setMinimumSize(QtCore.QSize(31, 31))
        self.programeControlLed.setObjectName("programeControlLed")
        self.gridLayout_2.addWidget(self.programeControlLed, 3, 5, 1, 1)
        self.keepHeightLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepHeightLed.sizePolicy().hasHeightForWidth())
        self.keepHeightLed.setSizePolicy(sizePolicy)
        self.keepHeightLed.setMinimumSize(QtCore.QSize(31, 31))
        self.keepHeightLed.setObjectName("keepHeightLed")
        self.gridLayout_2.addWidget(self.keepHeightLed, 3, 1, 1, 1)
        self.stopLed = QMyLed(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopLed.sizePolicy().hasHeightForWidth())
        self.stopLed.setSizePolicy(sizePolicy)
        self.stopLed.setMinimumSize(QtCore.QSize(31, 31))
        self.stopLed.setObjectName("stopLed")
        self.gridLayout_2.addWidget(self.stopLed, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(141, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.XEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.XEdit.setEnabled(False)
        self.XEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.XEdit.setFont(font)
        self.XEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.XEdit.setObjectName("XEdit")
        self.gridLayout_5.addWidget(self.XEdit, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 2, 1, 1)
        self.phiEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.phiEdit.setEnabled(False)
        self.phiEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.phiEdit.setFont(font)
        self.phiEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phiEdit.setObjectName("phiEdit")
        self.gridLayout_5.addWidget(self.phiEdit, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.YEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.YEdit.setEnabled(False)
        self.YEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.YEdit.setFont(font)
        self.YEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.YEdit.setObjectName("YEdit")
        self.gridLayout_5.addWidget(self.YEdit, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 2, 1, 1)
        self.thetaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.thetaEdit.setEnabled(False)
        self.thetaEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.thetaEdit.setFont(font)
        self.thetaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.thetaEdit.setObjectName("thetaEdit")
        self.gridLayout_5.addWidget(self.thetaEdit, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.HEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.HEdit.setEnabled(False)
        self.HEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.HEdit.setFont(font)
        self.HEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HEdit.setObjectName("HEdit")
        self.gridLayout_5.addWidget(self.HEdit, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 2, 1, 1)
        self.psiEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.psiEdit.setEnabled(False)
        self.psiEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.psiEdit.setFont(font)
        self.psiEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.psiEdit.setObjectName("psiEdit")
        self.gridLayout_5.addWidget(self.psiEdit, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.alphaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.alphaEdit.setEnabled(False)
        self.alphaEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.alphaEdit.setFont(font)
        self.alphaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout_5.addWidget(self.alphaEdit, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 2, 1, 1)
        self.pEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.pEdit.setEnabled(False)
        self.pEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pEdit.setFont(font)
        self.pEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pEdit.setObjectName("pEdit")
        self.gridLayout_5.addWidget(self.pEdit, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 4, 0, 1, 1)
        self.betaEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.betaEdit.setEnabled(False)
        self.betaEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.betaEdit.setFont(font)
        self.betaEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.betaEdit.setObjectName("betaEdit")
        self.gridLayout_5.addWidget(self.betaEdit, 4, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 4, 2, 1, 1)
        self.qEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.qEdit.setEnabled(False)
        self.qEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.qEdit.setFont(font)
        self.qEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.qEdit.setObjectName("qEdit")
        self.gridLayout_5.addWidget(self.qEdit, 4, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 5, 0, 1, 1)
        self.VtEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.VtEdit.setEnabled(False)
        self.VtEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.VtEdit.setFont(font)
        self.VtEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VtEdit.setObjectName("VtEdit")
        self.gridLayout_5.addWidget(self.VtEdit, 5, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setMinimumSize(QtCore.QSize(81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 5, 2, 1, 1)
        self.rEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.rEdit.setEnabled(False)
        self.rEdit.setMinimumSize(QtCore.QSize(70, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.rEdit.setFont(font)
        self.rEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rEdit.setObjectName("rEdit")
        self.gridLayout_5.addWidget(self.rEdit, 5, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(16, -1, 16, -1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.climb1Button = QtWidgets.QPushButton(self.groupBox)
        self.climb1Button.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.climb1Button.setFont(font)
        self.climb1Button.setObjectName("climb1Button")
        self.gridLayout.addWidget(self.climb1Button, 0, 1, 1, 1)
        self.turnLeftButton = QtWidgets.QPushButton(self.groupBox)
        self.turnLeftButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.turnLeftButton.setFont(font)
        self.turnLeftButton.setObjectName("turnLeftButton")
        self.gridLayout.addWidget(self.turnLeftButton, 0, 2, 1, 1)
        self.landingButton = QtWidgets.QPushButton(self.groupBox)
        self.landingButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.landingButton.setFont(font)
        self.landingButton.setObjectName("landingButton")
        self.gridLayout.addWidget(self.landingButton, 1, 0, 1, 1)
        self.climb2Button = QtWidgets.QPushButton(self.groupBox)
        self.climb2Button.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.climb2Button.setFont(font)
        self.climb2Button.setObjectName("climb2Button")
        self.gridLayout.addWidget(self.climb2Button, 1, 1, 1, 1)
        self.turnRightButton = QtWidgets.QPushButton(self.groupBox)
        self.turnRightButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.turnRightButton.setFont(font)
        self.turnRightButton.setObjectName("turnRightButton")
        self.gridLayout.addWidget(self.turnRightButton, 1, 2, 1, 1)
        self.keepHeightButton = QtWidgets.QPushButton(self.groupBox)
        self.keepHeightButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.keepHeightButton.setFont(font)
        self.keepHeightButton.setObjectName("keepHeightButton")
        self.gridLayout.addWidget(self.keepHeightButton, 2, 0, 1, 1)
        self.decline1Button = QtWidgets.QPushButton(self.groupBox)
        self.decline1Button.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.decline1Button.setFont(font)
        self.decline1Button.setObjectName("decline1Button")
        self.gridLayout.addWidget(self.decline1Button, 2, 1, 1, 1)
        self.keepDirectButton = QtWidgets.QPushButton(self.groupBox)
        self.keepDirectButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.keepDirectButton.setFont(font)
        self.keepDirectButton.setObjectName("keepDirectButton")
        self.gridLayout.addWidget(self.keepDirectButton, 2, 2, 1, 1)
        self.decline2Button = QtWidgets.QPushButton(self.groupBox)
        self.decline2Button.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.decline2Button.setFont(font)
        self.decline2Button.setObjectName("decline2Button")
        self.gridLayout.addWidget(self.decline2Button, 3, 1, 1, 1)
        self.programmedControlButton = QtWidgets.QPushButton(self.groupBox)
        self.programmedControlButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.programmedControlButton.setFont(font)
        self.programmedControlButton.setObjectName("programmedControlButton")
        self.gridLayout.addWidget(self.programmedControlButton, 3, 2, 1, 1)
        self.takeOffButton = QtWidgets.QPushButton(self.groupBox)
        self.takeOffButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.takeOffButton.setFont(font)
        self.takeOffButton.setObjectName("takeOffButton")
        self.gridLayout.addWidget(self.takeOffButton, 0, 0, 1, 1)
        self.saveFigButton = QtWidgets.QPushButton(self.groupBox)
        self.saveFigButton.setMinimumSize(QtCore.QSize(90, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.saveFigButton.setFont(font)
        self.saveFigButton.setObjectName("saveFigButton")
        self.gridLayout.addWidget(self.saveFigButton, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(900, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.threeDView = QmyFigureCanvas(self.groupBox_3)
        self.threeDView.setObjectName("threeDView")
        self.verticalLayout_3.addWidget(self.threeDView)
        self.mapView = QmyFigureCanvas(self.groupBox_3)
        self.mapView.setObjectName("mapView")
        self.verticalLayout_3.addWidget(self.mapView)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.heightView = QmyFigureCanvas(self.groupBox_4)
        self.heightView.setObjectName("heightView")
        self.verticalLayout_2.addWidget(self.heightView)
        self.thetaView = QmyFigureCanvas(self.groupBox_4)
        self.thetaView.setObjectName("thetaView")
        self.verticalLayout_2.addWidget(self.thetaView)
        self.phiView = QmyFigureCanvas(self.groupBox_4)
        self.phiView.setObjectName("phiView")
        self.verticalLayout_2.addWidget(self.phiView)
        self.psiView = QmyFigureCanvas(self.groupBox_4)
        self.psiView.setObjectName("psiView")
        self.verticalLayout_2.addWidget(self.psiView)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        MainRhapsody.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainRhapsody)
        self.statusbar.setObjectName("statusbar")
        MainRhapsody.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainRhapsody)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainRhapsody)
        self.action_3.setObjectName("action_3")
        self.actParameterTitle = QtWidgets.QAction(MainRhapsody)
        self.actParameterTitle.setObjectName("actParameterTitle")
        self.actParameterLegend = QtWidgets.QAction(MainRhapsody)
        self.actParameterLegend.setObjectName("actParameterLegend")
        self.actParamenterLabel = QtWidgets.QAction(MainRhapsody)
        self.actParamenterLabel.setObjectName("actParamenterLabel")
        self.action_7 = QtWidgets.QAction(MainRhapsody)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainRhapsody)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainRhapsody)
        self.action_9.setObjectName("action_9")

        self.retranslateUi(MainRhapsody)
        QtCore.QMetaObject.connectSlotsByName(MainRhapsody)

    def retranslateUi(self, MainRhapsody):
        _translate = QtCore.QCoreApplication.translate
        MainRhapsody.setWindowTitle(_translate("MainRhapsody", "MainRhapsody"))
        self.groupBox_6.setTitle(_translate("MainRhapsody", "飞行状态"))
        self.label_13.setText(_translate("MainRhapsody", "向左"))
        self.label.setText(_translate("MainRhapsody", "起飞"))
        self.label_6.setText(_translate("MainRhapsody", "下滑1"))
        self.label_28.setText(_translate("MainRhapsody", "停止"))
        self.label_2.setText(_translate("MainRhapsody", "着陆"))
        self.label_15.setText(_translate("MainRhapsody", "定向"))
        self.label_3.setText(_translate("MainRhapsody", "定高平飞"))
        self.label_4.setText(_translate("MainRhapsody", "爬升1"))
        self.label_14.setText(_translate("MainRhapsody", "向右"))
        self.label_12.setText(_translate("MainRhapsody", "下滑2"))
        self.label_16.setText(_translate("MainRhapsody", "程控飞行"))
        self.label_5.setText(_translate("MainRhapsody", "爬升2"))
        self.groupBox_2.setTitle(_translate("MainRhapsody", "参数显示"))
        self.label_11.setText(_translate("MainRhapsody", "距离:"))
        self.XEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_19.setText(_translate("MainRhapsody", "滚转角:"))
        self.phiEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_10.setText(_translate("MainRhapsody", "侧向位置:"))
        self.YEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_18.setText(_translate("MainRhapsody", "俯仰角:"))
        self.thetaEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_9.setText(_translate("MainRhapsody", "高度:"))
        self.HEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_17.setText(_translate("MainRhapsody", "偏航角:"))
        self.psiEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_8.setText(_translate("MainRhapsody", "迎角:"))
        self.alphaEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_20.setText(_translate("MainRhapsody", "滚转角速率:"))
        self.pEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_7.setText(_translate("MainRhapsody", "侧滑角:"))
        self.betaEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_21.setText(_translate("MainRhapsody", "俯仰角速率:"))
        self.qEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_46.setText(_translate("MainRhapsody", "空速:"))
        self.VtEdit.setText(_translate("MainRhapsody", "     0"))
        self.label_45.setText(_translate("MainRhapsody", "偏航角速率:"))
        self.rEdit.setText(_translate("MainRhapsody", "     0"))
        self.groupBox.setTitle(_translate("MainRhapsody", "控制指令"))
        self.climb1Button.setText(_translate("MainRhapsody", "爬升1"))
        self.turnLeftButton.setText(_translate("MainRhapsody", "向左"))
        self.landingButton.setText(_translate("MainRhapsody", "着陆"))
        self.climb2Button.setText(_translate("MainRhapsody", "爬升2"))
        self.turnRightButton.setText(_translate("MainRhapsody", "向右"))
        self.keepHeightButton.setText(_translate("MainRhapsody", "定高平飞"))
        self.decline1Button.setText(_translate("MainRhapsody", "下滑1"))
        self.keepDirectButton.setText(_translate("MainRhapsody", "定向"))
        self.decline2Button.setText(_translate("MainRhapsody", "下滑2"))
        self.programmedControlButton.setText(_translate("MainRhapsody", "程控飞行"))
        self.takeOffButton.setText(_translate("MainRhapsody", "起飞"))
        self.saveFigButton.setText(_translate("MainRhapsody", "保存图像"))
        self.groupBox_3.setTitle(_translate("MainRhapsody", "三维航迹"))
        self.groupBox_4.setTitle(_translate("MainRhapsody", "飞行参数曲线"))
        self.action_2.setText(_translate("MainRhapsody", "关于软件"))
        self.action_3.setText(_translate("MainRhapsody", "关于课题组"))
        self.actParameterTitle.setText(_translate("MainRhapsody", "飞行参数图标字体设置"))
        self.actParameterLegend.setText(_translate("MainRhapsody", "飞行参数图例字体设置"))
        self.actParamenterLabel.setText(_translate("MainRhapsody", "飞行参数数据标签字体设置"))
        self.action_7.setText(_translate("MainRhapsody", "地图数据标签字体设置"))
        self.action_8.setText(_translate("MainRhapsody", "地图图例字体设置"))
        self.action_9.setText(_translate("MainRhapsody", "地图图标字体设置"))
from QMyLed import QMyLed
from myFigureCanvas import QmyFigureCanvas
import res_rc
